"""add_user_models

Revision ID: 8c774cbe946f
Revises: 
Create Date: 2026-06-26 20:58:32.489349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c774cbe946f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('wx_openid', sa.String(length=64), nullable=True, comment='微信OpenID'),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'RETAILER', 'OPERATOR', 'DESIGNER', name='userrole'), nullable=False),
    sa.Column('level', sa.Enum('NORMAL', 'SILVER', 'GOLD', 'PLATINUM', name='retailerlevel'), nullable=False, comment='零售商等级'),
    sa.Column('credit_limit', sa.Integer(), nullable=False, comment='账期总额度(分)'),
    sa.Column('credit_balance', sa.Integer(), nullable=False, comment='已用额度(分)'),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'ACTIVE', 'FROZEN', name='userstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wx_openid')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('designer_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio', sa.JSON(), nullable=True, comment='作品集'),
    sa.Column('specializations', sa.JSON(), nullable=True, comment='擅长领域'),
    sa.Column('active_orders_count', sa.Integer(), nullable=False, comment='进行中的订单数'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('retailer_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False, comment='公司名称'),
    sa.Column('business_license', sa.String(length=100), nullable=False, comment='营业执照号'),
    sa.Column('contact_person', sa.String(length=50), nullable=False, comment='联系人'),
    sa.Column('purchase_history_summary', sa.JSON(), nullable=True, comment='AI生成的购买画像摘要'),
    sa.Column('preferred_categories', sa.JSON(), nullable=True, comment='偏好品类ID列表'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retailer_profiles')
    op.drop_table('designer_profiles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
