"""add_product_models

Revision ID: a1b2c3d4e5f6
Revises: 8c774cbe946f
Create Date: 2026-06-26 21:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '8c774cbe946f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('parent_id', sa.Uuid(), nullable=True, comment='父品类ID（树形结构）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='品类名称'),
    sa.Column('icon', sa.String(length=500), nullable=True, comment='图标URL'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active|hidden'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('category_id', sa.Uuid(), nullable=True, comment='所属品类'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='商品名称'),
    sa.Column('images', sa.JSON(), nullable=True, comment='商品图片URL列表'),
    sa.Column('description', sa.Text(), nullable=True, comment='商品描述'),
    sa.Column('specs', sa.JSON(), nullable=True, comment='规格参数JSON'),
    sa.Column('age_range', sa.String(length=20), nullable=True, comment='适龄段: 0-3岁/3-6岁/6岁+'),
    sa.Column('safety_certifications', sa.JSON(), nullable=True, comment='安全认证: [{"name":"3C认证","icon":"url"}]'),
    sa.Column('is_virtual', sa.Boolean(), nullable=False, comment='是否虚拟商品（店面设计服务）'),
    sa.Column('virtual_detail', sa.JSON(), nullable=True, comment='虚拟商品详情: {area,style,budget}'),
    sa.Column('stock', sa.Integer(), nullable=True, comment='库存（虚拟商品为null）'),
    sa.Column('min_order_qty', sa.Integer(), nullable=False, comment='最低起批量'),
    sa.Column('pricing_rules', sa.JSON(), nullable=False, comment='阶梯定价矩阵'),
    sa.Column('ai_knowledge_id', sa.Uuid(), nullable=True, comment='关联AI知识库条目(Phase 2)'),
    sa.Column('status', sa.Enum('ON_SALE', 'OFF_SALE', 'DELETED', name='productstatus'), nullable=False, comment='商品状态'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('categories')
    # ### end Alembic commands ###
